### ISSUE TITLE
Chrome extension has old manifest version

### ISSUE THREAD

**Issue by ioistired** [feross/CMSploit#1]
Chrome sez:

> Support for manifest version 1 is being phased out. Please upgrade to version 2.

This is a total pain, because after a while, this extension won't work _at all_.

**Comment by feross** [comment]
Thanks for the heads up, ben. Are you actually using this extension? I'm not really supporting it atm because I figured that no one was actually using it. The NodeJS and and PhantomJS implementations work a lot better, imo.

If you're still interested, maybe you can take a look and send a pull request?

**Comment by ioistired** [comment]
Yes, I am using this extension, and loving it! I would like it more,
however, if it could be updated to reflect the implementations from the
NodeJS and PhantomJS implementations. Also, I can't code, so I wouldn't
know how to update the manifest.

Thanks,

Benjamin Mintz
benjabean1@gmail.com
